<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rocker-bogie">

<!-- INCLUDED FILES -->
    <xacro:include filename="rocker/__rocker.xacro"/>
    <xacro:include filename="bogie/__bogie.xacro"/>
    <xacro:include filename="suspension_beam.xacro"/>
    <xacro:include filename="wheel.xacro"/>

    <!-- TODO NO SUPPORT FOR CLOSED CHAINSD UNTIL URDF 2.0 TODO -->
    <!--xacro:include filename="rocker-bogie/differential.xacro"/-->

<!-- PROPERIES -->
    <!-- WHEELS POSITIONS -->
    <xacro:property name="wheel_base_f" value=".550"/>
    <xacro:property name="wheel_base_m" value=".600"/>
    <xacro:property name="wheel_base_b" value=".500"/>

    <!--xacro:property name="h_bogie" value=".100"/-->
    <!--xacro:property name="l_bogie" value=".305"/-->

    <xacro:property name="h_wheel" value=".250"/>
    <xacro:property name="l_wheel_f" value=".305"/>
    <!--xacro:property name="l_wheel_m" value=".160"/>
    <xacro:property name="l_wheel_b" value=".160"/-->

    <!-- CUSTOM SIM PROPS -->
    <xacro:property name="h_bogie" value=".170"/>
    <xacro:property name="l_bogie" value=".305"/>
    <xacro:property name="l_wheel_m" value=".200"/>
    <xacro:property name="l_wheel_b" value=".200"/>

    <!-- ELEMENTS DIAMETERS -->
    <xacro:property name="suspension_beam_length" value=".600"/>
    <xacro:property name="suspension_beam_radius" value=".025"/>

    <xacro:property name="rocker_bearing_length" value=".050"/>
    <xacro:property name="rocker_bearing_radius" value=".035"/>

    <xacro:property name="bogie_bearing_length" value=".100"/>
    <xacro:property name="bogie_bearing_radius" value=".030"/>

    <xacro:property name="wheel_width" value=".100"/>
    <xacro:property name="wheel_radius" value=".100"/>

<!-- RELATIVE VARIABLES -->
    <xacro:property name="f_wheel_deviation" value="${(wheel_base_f - wheel_base_m)/2}"/>
    <xacro:property name="b_wheel_deviation" value="${(wheel_base_b - wheel_base_m)/2}"/>
    <xacro:property name="wheel_offset" value=".100"/>

<!-- MAIN LINK -->
    <xacro:suspension_beam name="suspension_beam"/>

<!-- SUSPENSION -->
    <xacro:rocker name="rocker_l" parent="suspension_beam" x="0" y="${wheel_base_m/2}"    z="0"/>
    <xacro:rocker name="rocker_r" parent="suspension_beam" x="0" y="${-wheel_base_m/2}"    z="0"/>

    <xacro:bogie name="bogie_l" parent="rocker_l_bearing" x="${-l_bogie}" y="0"  z="${-h_bogie}" side="1"/>
    <xacro:bogie name="bogie_r" parent="rocker_r_bearing" x="${-l_bogie}" y="0"  z="${-h_bogie}" side="-1"/>

<!-- WHEELS -->

    <xacro:wheel name="fl" parent="rocker_l_bearing" x="${l_wheel_f}"    z="${-h_wheel}"    y="${+f_wheel_deviation + wheel_offset}" u="1"/>
    <xacro:wheel name="fr" parent="rocker_r_bearing" x="${l_wheel_f}"    z="${-h_wheel}"    y="${-f_wheel_deviation - wheel_offset}" u="1"/>

    <xacro:wheel name="ml" parent="bogie_l_bearing"  x="${l_wheel_m}"    z="${-h_wheel+h_bogie}"    y="${+wheel_offset}" u=".7"/>
    <xacro:wheel name="mr" parent="bogie_r_bearing"  x="${l_wheel_m}"    z="${-h_wheel+h_bogie}"    y="${-wheel_offset}" u=".7"/>

    <xacro:wheel name="bl" parent="bogie_l_bearing"  x="${-l_wheel_b}"   z="${-h_wheel+h_bogie}"    y="${+b_wheel_deviation + wheel_offset}" u="1"/>
    <xacro:wheel name="br" parent="bogie_r_bearing"  x="${-l_wheel_b}"   z="${-h_wheel+h_bogie}"    y="${-b_wheel_deviation - wheel_offset}" u="1"/>


<!-- MY DIFFERENTIAL PLUGIN -->
    <!--gazebo>
        <plugin name="differential" filename="libDifferential.so">
            <leftJoint>rocker_l_bearing_joint</leftJoint>
            <rightJoint>rocker_r_bearing_joint</rightJoint>
        </plugin>
    </gazebo-->

    <gazebo>
        <plugin name="differential_pid" filename="libDifferentialPID.so">
            <leftJoint>rocker_l_bearing_joint</leftJoint>
            <rightJoint>rocker_r_bearing_joint</rightJoint>
            <topic>/rover/differential_pid</topic>
            <Kp>3000</Kp>
            <Ki>0</Ki>
            <Kd>10000</Kd>
            <limit>10000</limit>
        </plugin>
    </gazebo>


</robot>
