<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="main_body">

<!-- GEOMETRY -->
    <xacro:macro name="main_body_geometry_1">
        <origin rpy="0 0 0" xyz="${x} ${y} ${z}"/>
        <geometry>
            <box size="${body_length} ${body_width} ${body_height}"/>
        </geometry>
    </xacro:macro>

    <!-- <xacro:macro name="main_body_geometry_2">
        <origin rpy="0 0 0" xyz="${body_length/2 + body_translation_x -.125} 0 ${body_height/2 + .050 + body_translation_x}"/>
        <geometry>
            <box size=".250 ${body_width} .100"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="main_body_geometry_3">
        <origin rpy="0 0 0" xyz="${-body_length/2 + body_translation_x +.050} 0 ${body_height/2 + .050 + body_translation_x}"/>
        <geometry>
            <box size=".100 ${body_width} .100"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="main_body_geometry_4">
        <origin rpy="0 0 0" xyz="${-body_length/2 + body_translation_x +.025 + 0.100 + 0.150} 0 ${body_height/2 + .050 + body_translation_x}"/>
        <geometry>
            <box size=".050 ${body_width} .100"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="main_body_geometry_5" params="side">
        <origin rpy="0 0 0" xyz="${body_translation_x} ${(body_width/2 - .025)*side} ${body_height/2 + .050 + body_translation_x}"/>
        <geometry>
            <box size="${body_length} .050 .100"/>
        </geometry>
    </xacro:macro> -->

<!-- VISUAL -->
    <xacro:macro name="main_body_visual">
        <origin xyz="-0.402 0.43 -0.294" rpy="1.57075 0 0"/>
        <geometry>
            <mesh filename="package://phobos_meshes/rover_stl/R.Assembly.STL" scale="0.001 0.001 0.001"/>
        </geometry>
    </xacro:macro>

<!-- MATERIAL -->
    <xacro:macro name="main_body_material">
        <material name="dark_gray">
            <color rgba=".2 .2 .3 1"/>
        </material>
    </xacro:macro>

<!-- LINK -->
    <xacro:macro name="main_body" params="name parent x y z">

    <!-- MAIN LINK -->
        <link name="${name}">
            <visual>
                <xacro:main_body_visual/>
                <xacro:main_body_material/>
            </visual>
            <collision>
                <xacro:main_body_geometry_1/>
            </collision>
    <!-- BOXES FOR STONES -->
            <!-- <visual>
                <xacro:main_body_geometry_2/>
                <xacro:main_body_material/>
            </visual>
            <collision>
                <xacro:main_body_geometry_2/>
            </collision>

            <visual>
                <xacro:main_body_geometry_3/>
                <xacro:main_body_material/>
            </visual>
            <collision>
                <xacro:main_body_geometry_3/>
            </collision>

            <visual>
                <xacro:main_body_geometry_4/>
                <xacro:main_body_material/>
            </visual>
            <collision>
                <xacro:main_body_geometry_4/>
            </collision>

            <visual>
                <xacro:main_body_geometry_5 side="1"/>
                <xacro:main_body_material/>
            </visual>
            <collision>
                <xacro:main_body_geometry_5 side="1"/>
            </collision>

            <visual>
                <xacro:main_body_geometry_5 side="0"/>
                <xacro:main_body_material/>
            </visual>
            <collision>
                <xacro:main_body_geometry_5 side="0"/>
            </collision>

            <visual>
                <xacro:main_body_geometry_5 side="-1"/>
                <xacro:main_body_material/>
            </visual>
            <collision>
                <xacro:main_body_geometry_5 side="-1"/>
            </collision> -->

            <inertial>
                 <mass value="16.958705"/>
                 <origin xyz="-0.151662 0.000004 -0.014131" rpy="0 0 0"/>
                 <inertia ixx="0.334161" ixy="-0.000002" ixz="0.010911" iyy="0.341848" iyz="0.000000" izz="0.436339"/>
            </inertial>
        </link>

        <gazebo reference="${name}">
            <mu1> .2 </mu1>
            <mu2> .2 </mu2>
            <material> Gazebo/Orange </material>
            <selfCollide> True </selfCollide>
        </gazebo>

        <joint name="${name}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="${name}"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </joint>
        <gazebo reference="${name}_joint">
            <stopCfm>0.8</stopCfm>
            <stopErp>0.5</stopErp>
            <provideFeedback>true</provideFeedback>
            <implicitSpringDamper>true</implicitSpringDamper>
            <fudgeFactor>0.0</fudgeFactor>
        </gazebo>

    </xacro:macro>

</robot>
