<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="link1">

<!-- GEOMETRY -->
    <xacro:macro name="link1_geometry_1">
        <origin rpy="0 0 0" xyz="${-link1_length/2} 0 0" />
        <geometry>
            <box size="${link1_length} ${link1_width} ${link1_height}"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="link1_geometry_2">
        <origin rpy="1.57075 0 0" xyz="${-link1_length} 0 ${link1_height/2}" />
        <geometry>
            <cylinder length="${link1_width}" radius="${link1_height}"/>
        </geometry>
    </xacro:macro>

<!-- MATERIAL -->
    <xacro:macro name="link1_material">
        <material name="light_blue">
            <color rgba=".3 .3 .6 1"/>
        </material>
    </xacro:macro>

<!-- LINK -->
    <xacro:macro name="link1" params="name parent x y z ">
        <link name="${name}">
            <visual>
                <xacro:link1_geometry_1/>
                <xacro:link1_material/>
            </visual>
            <visual>
                <xacro:link1_geometry_2/>
                <xacro:link1_material/>
            </visual>
            <collision>
                <xacro:link1_geometry_1/>
            </collision>
            <collision>
                <xacro:link1_geometry_2/>
            </collision>
            <inertial>
                 <origin rpy="0 0 0" xyz="${-link1_length/2} 0 0" />
                 <mass value="1"/>
                 <inertia ixx=".003" ixy="0.000" ixz="0.000" iyy=".003" iyz="0.000" izz=".003"/>
            </inertial>
        </link>
        <gazebo reference="${name}">
            <mu1> .2 </mu1>
            <mu2> .2 </mu2>
            <material> Gazebo/Grey </material>
            <selfCollide>True</selfCollide>
        </gazebo>

        <joint name="${name}_joint" type="revolute">
            <parent link="${parent}"/>
            <child link="${name}"/>
            <origin rpy="0 1.57075 0" xyz="${x} ${y} ${z}"/>
            <axis xyz="0 1 0"/>
            <limit effort="100" velocity="1" lower="-1.25" upper="1.6"/>
            <dynamics damping="1"/>
        </joint>
        <!--gazebo reference="${name}_joint">
            <stopCfm>0.5</stopCfm>
            <stopErp>0.8</stopErp>
            <provideFeedback>true</provideFeedback>
            <implicitSpringDamper>true</implicitSpringDamper>
            <fudgeFactor>0.0</fudgeFactor>
        </gazebo-->
        <gazebo>
            <plugin name="${name}_joint_limiter" filename="libJointLimiter.so">
                <joint>${name}_joint</joint>
                <topic>/rover/${name}_velocity_controller</topic>
                <lower>-1.25</lower>
                <upper>1.6</upper>
            </plugin>
        </gazebo>
        <gazebo>
            <plugin name="${name}_controller" filename="libControllerPID.so">
                <joint>${name}_joint</joint>
                <topic>/rover/${name}_velocity_controller</topic>
                <Kp>30</Kp>
                <Ki>3</Ki>
                <Kd>2</Kd>
            </plugin>
        </gazebo>

        <!--transmission name="${name}_transmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${name}_joint">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${name}_motor">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission-->

    </xacro:macro>
</robot>
