<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="link_4_finger">

<!-- GEOMETRY -->
    <xacro:macro name="link_4_finger_geometry_1">
        <origin rpy="0 0 0" xyz="${link_4_finger_length/4} 0 0" />
        <geometry>
            <box size="${link_4_finger_length/2} ${link_4_finger_width} ${link_4_finger_height}"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="link_4_finger_geometry_2">
        <origin rpy="0 0 ${1*side}" xyz="${link_4_finger_length/2 + 0.007} ${0.013*side} 0" />
        <geometry>
            <box size="0.033 ${link_4_finger_width} ${link_4_finger_height}"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="link_4_finger_geometry_3">
        <origin rpy="1.57075 0 0" xyz="${link_4_finger_length/2-0.01} ${side*0.027} ${link_4_finger_height/2}" />
        <geometry>
            <box size="0.05 0.003 0.003"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="link_4_finger_geometry_4">
        <origin rpy="1.57075 0 0" xyz="${link_4_finger_length/2-0.01} ${side*0.027} ${-link_4_finger_height/2}" />
        <geometry>
            <box size="0.05 0.003 0.003"/>
        </geometry>
    </xacro:macro>

    <!-- <xacro:macro name="link_4_finger_geometry_3">
        <origin rpy="0 0 ${1*side}" xyz="${link_4_finger_length/2} 0 0" />
        <geometry>
            <cylinder length="${link_4_finger_height}" radius="${link_4_finger_width/2}"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="link_4_finger_geometry_4">
        <origin rpy="0 0 ${1*side}" xyz="${link_4_finger_length/2+link_4_finger_length/6*1.414} ${link_4_finger_length/6*1.414*side} 0" />
        <geometry>
            <cylinder length="${link_4_finger_height}" radius="${link_4_finger_width/2}"/>
        </geometry>
    </xacro:macro> -->

<!-- VISUAL -->
    <xacro:macro name="link_4_finger_visual">
        <origin xyz="0.195 -0.078 -0.571" rpy="1.59 -0.18 -1.75"/>
        <geometry>
            <mesh filename="package://phobos_meshes/rover_stl/ruchoma_cz.STL" scale="0.001 0.001 0.001"/>
        </geometry>
    </xacro:macro>

<!-- MATERIAL -->
    <xacro:macro name="link_4_finger_material">
        <material name="link_4_finger_color">
            <color rgba=".4 .4 .8 1"/>
        </material>
    </xacro:macro>

<!-- LINK -->
    <xacro:macro name="link_4_finger" params="name parent x y z side">

        <link name="${name}">

            <!-- <visual>
                <xacro:link_4_finger_visual/>
                <xacro:link_4_finger_material/>
            </visual> -->

            <!-- <visual>
                <xacro:link_4_finger_geometry_1/>
                <xacro:link_4_finger_material/>
            </visual>
            <visual>
                <xacro:link_4_finger_geometry_2/>
                <xacro:link_4_finger_material/>
            </visual>
            <visual>
                <xacro:link_4_finger_geometry_3/>
                <xacro:link_4_finger_material/>
            </visual>
            <visual>
                <xacro:link_4_finger_geometry_4/>
                <xacro:link_4_finger_material/>
            </visual> -->

            <collision>
                <xacro:link_4_finger_geometry_1/>
            </collision>
            <collision>
                <xacro:link_4_finger_geometry_2/>
            </collision>
            <collision>
                <xacro:link_4_finger_geometry_3/>
            </collision>
            <collision>
                <xacro:link_4_finger_geometry_4/>
            </collision>

            <inertial>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <mass value=".2"/>
                <inertia ixx=".0003" ixy="0.000" ixz="0.000" iyy=".0003" iyz="0.000" izz=".0003"/>
            </inertial>
        </link>
        <gazebo reference="${name}">
            <mu1> 10 </mu1>
            <mu2> 10 </mu2>
            <material> Gazebo/Grey </material>
            <selfCollide>True</selfCollide>
        </gazebo>

        <joint name="${name}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="${name}"/>
            <origin rpy="0 0 0" xyz="${x} ${y} ${z}"/>
        </joint>
        <!--gazebo reference="${name}_joint">
            <stopCfm>0.8</stopCfm>
            <stopErp>0.5</stopErp>
            <provideFeedback>true</provideFeedback>
            <implicitSpringDamper>true</implicitSpringDamper>
            <fudgeFactor>0.0</fudgeFactor>
        </gazebo-->
        <!-- <gazebo>
            <plugin name="joint_limiter_${name}" filename="libJointLimiter.so">
                <joint>${name}_joint</joint>
                <topic>/simulation/controller/vel/${name}</topic>
                <lower>0</lower>
                <upper>${link_4_width/2 - link_4_finger_width}</upper>
            </plugin>
        </gazebo>
        <gazebo>
            <plugin name="joint_encoder_${name}" filename="libJointEncoder.so">
                <joint>${name}_joint</joint>
                <topic>/simulation/encoder/abs/${name}</topic>
                <lower>0</lower>
                <upper>${link_4_width/2 - link_4_finger_width}</upper>
                <absolute>1</absolute>
                <resolution>10000</resolution>
            </plugin>
        </gazebo>
        <gazebo>
            <plugin name="joint_encoder_${name}" filename="libJointEncoder.so">
                <joint>${name}_joint</joint>
                <topic>/simulation/encoder/abs/${name}</topic>
                <lower>0</lower>
                <upper>${link_4_width/2 - link_4_finger_width}</upper>
                <absolute>1</absolute>
                <resolution>10000</resolution>
            </plugin>
        </gazebo>
        <gazebo>
            <plugin name="joint_controller${name}" filename="libControllerPID.so">
                <joint>${name}_joint</joint>
                <topic>/simulation/controller/vel/${name}</topic>
                <Kp>20</Kp>
                <Ki>2</Ki>
                <Kd>5</Kd>
            </plugin>
        </gazebo> -->


        <!--transmission name="${name}_transmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${name}_joint">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${name}_motor">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission-->

    </xacro:macro>
</robot>
