<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="link3">

<!-- GEOMETRY -->
    <xacro:macro name="link3_geometry">
        <origin rpy="0 0 0" xyz="${link3_length/2} 0 0" />
        <geometry>
            <box size="${link3_length} ${link3_width} ${link3_height}"/>
        </geometry>
    </xacro:macro>

<!-- MATERIAL -->
    <xacro:macro name="link3_material">
        <material name="link3_color">
            <color rgba=".4 .4 .8 1"/>
        </material>
    </xacro:macro>

<!-- LINK -->
    <xacro:macro name="link3" params="name parent x y z">

        <link name="${name}">
            <visual>
                <xacro:link3_geometry/>
                <xacro:link3_material/>
            </visual>
            <collision>
                <xacro:link3_geometry/>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${link3_length/2} 0 ${link3_height/2}" />
                <mass value="1"/>
                <inertia ixx=".003" ixy="0.000" ixz="0.000" iyy=".003" iyz="0.000" izz=".003"/>
            </inertial>
        </link>
        <gazebo reference="${name}">
            <mu1> .2 </mu1>
            <mu2> .2 </mu2>
            <material> Gazebo/Grey </material>
            <selfCollide>True</selfCollide>
        </gazebo>

        <joint name="${name}_joint" type="revolute">
            <parent link="${parent}"/>
            <child link="${name}"/>
            <origin rpy="0 0 0" xyz="${x} ${y} ${z}"/>
            <axis xyz="0 -1 0"/>
            <limit effort="30" velocity="1" lower="-2.3" upper="1.1"/>
            <dynamics damping="1"/>
        </joint>
        <!--gazebo reference="${name}_joint">
            <stopCfm>0.8</stopCfm>
            <stopErp>0.5</stopErp>
            <provideFeedback>true</provideFeedback>
            <implicitSpringDamper>true</implicitSpringDamper>
            <fudgeFactor>0.0</fudgeFactor>
        </gazebo-->
        <gazebo>
            <plugin name="${name}_joint_limiter" filename="libJointLimiter.so">
                <joint>${name}_joint</joint>
                <topic>/rover/${name}_velocity_controller</topic>
                <lower>-2.3</lower>
                <upper>1.1</upper>
            </plugin>
        </gazebo>
        <gazebo>
            <plugin name="${name}_controller" filename="libControllerPID.so">
                <joint>${name}_joint</joint>
                <topic>/rover/${name}_velocity_controller</topic>
                <Kp>20</Kp>
                <Ki>0</Ki>
                <Kd>2</Kd>
            </plugin>
        </gazebo>


        <gazebo reference="${name}">
            <mu1> .2 </mu1>
            <mu2> .2 </mu2>
            <material> Gazebo/Blue </material>
            <selfCollide>True</selfCollide>
            <!--kp>1.0</kp>
            <kd>1.0</kd>
            <stopCfm>0.8</stopCfm>
            <stopErp>0.5</stopErp>
            <provideFeedback>true</provideFeedback>
            <cfmDamping>true</cfmDamping>
            <fudgeFactor>0.0</fudgeFactor-->
        </gazebo>

        <!--transmission name="${name}_transmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${name}_joint">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${name}_motor">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission-->

    </xacro:macro>
</robot>
