<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="bogie">

<!-- INCLUDE -->
    <xacro:include filename="bogie_bearing.xacro"/>
    <xacro:include filename="bogie_link_1.xacro"/>
    <xacro:include filename="bogie_link_2.xacro"/>

<!-- PROPERTIES -->
    <xacro:property name="bogie_link_1_length"      value=".215"/>
    <xacro:property name="bogie_link_1_width"       value=".040"/>
    <xacro:property name="bogie_link_1_height"      value=".050"/>
    <xacro:property name="bogie_link_1_x"            value=".000"/>
    <xacro:property name="bogie_link_1_y"            value=".000"/>
    <xacro:property name="bogie_link_1_z"            value=".000"/>
    <xacro:property name="bogie_link_1_offset_x"    value="${bogie_link_1_length/2}"/>
    <xacro:property name="bogie_link_1_offset_y"    value=".025"/>
    <xacro:property name="bogie_link_1_offset_z"    value=".000"/>
    <xacro:property name="bogie_link_1_pitch"        value="-0.38"/>

    <xacro:property name="bogie_link_2_length"      value=".215"/>
    <xacro:property name="bogie_link_2_width"       value=".040"/>
    <xacro:property name="bogie_link_2_height"      value=".050"/>
    <xacro:property name="bogie_link_2_x"            value=".000"/>
    <xacro:property name="bogie_link_2_y"            value=".000"/>
    <xacro:property name="bogie_link_2_z"            value=".000"/>
    <xacro:property name="bogie_link_2_offset_x"    value="${-bogie_link_2_length/2}"/>
    <xacro:property name="bogie_link_2_offset_y"    value="-.025"/>
    <xacro:property name="bogie_link_2_offset_z"    value=".000"/>
    <xacro:property name="bogie_link_2_pitch"        value="0.38"/>

<!-- LINKS -->
    <xacro:macro name="bogie" params="name parent x y z side">

        <xacro:bogie_bearing name="${name}_bearing" parent="${parent}" x="${x}" y="${y}" z="${z}" side="${side}"/>

        <!-- <xacro:bogie_link_1 name="${name}_link_1" parent="${name}_bearing"
            x="${bogie_link_1_x}" y="${-bogie_link_1_y}"  z="${bogie_link_1_z}"
            pitch="${-bogie_link_1_pitch}" side="${side}"/>

        <xacro:bogie_link_2 name="${name}_link_2" parent="${name}_bearing"
            x="${bogie_link_2_x}" y="${-bogie_link_2_y}"  z="${bogie_link_2_z}"
            pitch="${-bogie_link_2_pitch}" side="${side}"/> -->

    </xacro:macro>


</robot>
