<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="bogie_link2">

<!-- GEOMETRY -->
    <xacro:macro name="bogie_link2_geometry_1">
        <origin rpy="0 0 0" xyz="${bogie_link2_offset_x} ${bogie_link2_offset_y*side} ${bogie_link2_offset_z}" />
        <geometry>
            <box size="${bogie_link2_length} ${bogie_link2_width} ${bogie_link2_height}"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="bogie_link2_geometry_2" params="side">
        <origin rpy="1.57075 0 0" xyz="${-bogie_link2_length/2 + bogie_link2_offset_x} ${bogie_link2_offset_y*side} ${bogie_link2_offset_z}" />
        <geometry>
            <cylinder length="${bogie_link2_width}" radius="${bogie_link2_height/2}"/>
        </geometry>
    </xacro:macro>

<!-- MATERIAL -->
    <xacro:macro name="bogie_link2_material">
        <material name="light_blue">
            <color rgba=".3 .3 .6 1"/>
        </material>
    </xacro:macro>

<!-- LINK -->
    <xacro:macro name="bogie_link2" params="name parent x y z pitch side">
        <link name="${name}">
            <visual>
                <xacro:bogie_link2_geometry_1/>
                <xacro:bogie_link2_material/>
            </visual>
            <visual>
                <xacro:bogie_link2_geometry_2 side="${side}"/>
                <xacro:bogie_link2_material/>
            </visual>
            <collision>
                <xacro:bogie_link2_geometry_1/>
            </collision>
            <collision>
                <xacro:bogie_link2_geometry_2 side="${side}"/>
            </collision>
            <inertial>
                 <origin rpy="0 0 0" xyz="${bogie_link2_offset_x} ${bogie_link2_offset_y*side} ${bogie_link2_offset_z}" />
                 <mass value="2"/>
                 <inertia ixx=".003" ixy="0.000" ixz="0.000" iyy=".003" iyz="0.000" izz=".003"/>
            </inertial>
        </link>
        <gazebo reference="${name}">
            <mu1> .2 </mu1>
            <mu2> .2 </mu2>
            <material> Gazebo/Blue </material>
            <selfCollide>True</selfCollide>
        </gazebo>

        <joint name="${name}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="${name}"/>
            <origin rpy="0 ${pitch} 0" xyz="${x} ${y} ${z}"/>
        </joint>

    </xacro:macro>
</robot>
