<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rover">

<!-- INCLUDED FILES -->
    <xacro:include filename="main_body.xacro"/>
    <xacro:include filename="tower_yaw.xacro"/>
    <xacro:include filename="tower_pitch.xacro"/>
    <xacro:include filename="../sensors/camera.xacro"/>

<!-- PROPERTIES -->
    <!-- <xacro:property name="body_length" value=".720"/>
    <xacro:property name="body_width" value=".400"/>
    <xacro:property name="body_height" value=".150"/> -->

    <xacro:property name="body_length" value=".570"/>
    <xacro:property name="body_width" value=".400"/>
    <xacro:property name="body_height" value=".250"/>

    <xacro:property name="body_translation_x" value="-.040"/>
    <xacro:property name="body_translation_z" value="-.0325"/>

    <xacro:property name="tower_pose_x" value="${-body_length/2 - +0.05}"/>
    <xacro:property name="tower_pose_y" value=".160"/>
    <xacro:property name="tower_pose_z" value="${body_height/2 + tower_yaw_height/2}"/>


    <xacro:property name="tower_yaw_height" value=".400"/>
    <xacro:property name="tower_yaw_radius" value=".025"/>

    <xacro:property name="tower_pitch_length" value=".100"/>
    <xacro:property name="tower_pitch_width" value=".150"/>
    <xacro:property name="tower_pitch_height" value=".050"/>


<!-- BODY -->
    <xacro:main_body name="main_body" parent="suspension_beam" x="${body_translation_x}" y="0" z="${body_translation_z}"/>

<!--TOWER -->
    <!-- <xacro:tower_yaw name="tower_yaw" parent="main_body" x="${tower_pose_x}" y="${tower_pose_y}" z="${tower_pose_z}"/>
    <xacro:tower_pitch name="tower_pitch" parent="tower_yaw" x="0" y="0" z="${tower_yaw_height/2}"/> -->

<!-- SENSORS -->
    <xacro:camera_link name="camera1" parent="main_body" x="${body_length/2 + camera_x/2 + body_translation_x}" y=".100" z="-.070" pitch="0"/>
    <xacro:camera_link name="camera2" parent="main_body" x="${body_length/2 + camera_x/2 + body_translation_x}" y="-.100" z="-.070" pitch="0"/>
    <!-- <xacro:camera_link name="camera3" parent="tower_pitch" x="${tower_pitch_length/2 + camera_x/2}" y="0" z="0" pitch="0"/> -->
    <!-- <xacro:camera_link name="camera5" parent="main_body" x="0" y="0" z="${-body_height/2 - camera_x/2 + body_translation_z}" pitch="1.57075"/> -->


</robot>
